version: "3.7"
services:
    backend:
      build: 
        context: ./backend
      image: be-the-hero-backend
      ports: 
        - "3000:3000"
      networks: 
        - backend        
      volumes: 
        - ./backend:/app
    frontend:
      build: 
        context: ./frontend
      image: be-the-hero-frontend
      ports: 
        - "8080:3000"
      networks: 
        - backend
        - frontend
      volumes: 
        - ./frontend:/app
        - /app/node_modules
        
networks: 
  backend:
  frontend:      